/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-variant": "#b8efd2",
        "on-tertiary-fixed-variant": "#665500",
        "on-secondary-fixed-variant": "#006289",
        "secondary": "#00668e",
        "error-dim": "#70030f",
        "tertiary-fixed-dim": "#efc900",
        "outline": "#52856d",
        "primary": "#006e3d",
        "on-primary": "#e7ffea",
        "on-error": "#fff7f6",
        "secondary-fixed": "#c6e7ff",
        "inverse-on-surface": "#87a394",
        "tertiary-dim": "#635200",
        "tertiary": "#705e00",
        "outline-variant": "#88bda3",
        "on-tertiary-container": "#5b4b00",
        "on-surface-variant": "#356953",
        "surface-bright": "#e8fff0",
        "error-container": "#f56965",
        "on-background": "#003a28",
        "secondary-fixed-dim": "#a6dbff",
        "on-secondary-container": "#00587b",
        "inverse-surface": "#001209",
        "surface-tint": "#006e3d",
        "surface-container-highest": "#b8efd2",
        "surface-container-low": "#d8fce8",
        "surface": "#e8fff0",
        "secondary-dim": "#00597d",
        "on-tertiary-fixed": "#453900",
        "error": "#ac3434",
        "primary-fixed": "#5df89f",
        "on-surface": "#003a28",
        "inverse-primary": "#5df89f",
        "on-secondary-fixed": "#004461",
        "tertiary-fixed": "#ffd709",
        "on-tertiary": "#fff8ec",
        "primary-dim": "#006035",
        "surface-dim": "#aae7c9",
        "primary-fixed-dim": "#4ce992",
        "primary-container": "#5df89f",
        "on-primary-fixed": "#004625",
        "surface-container-high": "#c2f3d9",
        "on-primary-container": "#005b31",
        "on-error-container": "#65000b",
        "secondary-container": "#c6e7ff",
        "tertiary-container": "#ffd709",
        "background": "#e8fff0",
        "surface-container": "#cdf8e1",
        "on-secondary": "#f5f9ff",
        "on-primary-fixed-variant": "#006638",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Lexend"],
        "body": ["Lexend"],
        "label": ["Lexend"]
      }
    },
  },
  plugins: [],
}
